"use client";
import {useEffect,useState} from "react";
import Loans from "./Loans"; import Acquisitions from "./Acquisitions";
import type {Locale} from "@/lib/i18n/config"; import type {FinanceProperty,LoanRecord,LoanDraft} from "@/lib/investment/loans"; import type {AcquisitionRecord,AcquisitionDraft} from "@/lib/investment/acquisition";
/** Sample-cabinet labels, one stable object per locale so the load effect runs once. */
const COPY = {
  fr: { loading: "Chargement…", loan: "Crédit principal", acq: "Résidence à étudier", next: "Organiser la seconde visite", note: "Dossier exemple" },
  en: { loading: "Loading…", loan: "Primary mortgage", acq: "Property to review", next: "Arrange second viewing", note: "Sample dossier" },
  de: { loading: "Laden…", loan: "Hauptdarlehen", acq: "Zu prüfendes Objekt", next: "Zweite Besichtigung organisieren", note: "Beispieldossier" },
  lu: { loading: "Luet…", loan: "Haaptkredit", acq: "Projet ze préiwen", next: "Zweet Visitt organiséieren", note: "Beispill Dossier" },
} as const;
export default function InvestmentWorkspace({locale,properties,section,datasetId}:{locale:Locale;properties:FinanceProperty[];section:"loans"|"acquisitions";datasetId:"real"|"fr"|"lu"}){const [loans,setLoans]=useState<LoanRecord[]>([]),[acqs,setAcqs]=useState<AcquisitionRecord[]>([]),[loading,setLoading]=useState(datasetId==="real");const copy=COPY[locale];useEffect(()=>{if(datasetId!=="real"){setLoans([{id:"sample-loan-1",propertyId:properties[0]?.id??"",unitId:null,name:copy.loan,bankName:"Spuerkeess",originalCents:42000000,balanceCents:28100000,balanceDate:"2026-08-23",annualRatePct:2.45,rateType:"fixed",remainingMonths:198,insuranceCents:4200,nextPaymentDate:"2026-10-05",fixedUntil:"2031-10-05",notes:copy.note,createdAt:"2024-01-01T00:00:00Z",updatedAt:"2026-08-23T00:00:00Z"}]);setAcqs([{id:"sample-acq-1",name:copy.acq,address:"Bertrange, Luxembourg",stage:"viewing",askingPriceCents:68500000,expectedRentCents:320000,bankName:"",financingStatus:"research",notaryName:"",nextAction:copy.next,nextActionDate:"2026-10-08",viewingDate:"2026-10-08",compromisDate:null,financeDeadline:null,notaryAppointmentDate:null,deedSignedDate:null,transferDate:null,handoverDate:null,notes:copy.note,createdAt:"2026-08-01T00:00:00Z",updatedAt:"2026-08-23T00:00:00Z"}]);setLoading(false);return;}Promise.all([fetch('/api/gestion/investment/loans').then(r=>r.json()),fetch('/api/gestion/investment/acquisitions').then(r=>r.json())]).then(([l,a])=>{setLoans(l.records??[]);setAcqs(a.records??[])}).finally(()=>setLoading(false));},[datasetId,properties,copy]);const saveLoan=async(d:LoanDraft,id?:string)=>{const old=loans.find(x=>x.id===id);const r=await fetch(`/api/gestion/investment/loans${id?`/${id}`:""}`,{method:id?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(id?{draft:d,expectedUpdatedAt:old?.updatedAt}:d)});if(!r.ok)throw Error("save");const x=(await r.json()).record;setLoans(v=>[...v.filter(q=>q.id!==x.id),x]);};const saveAcq=async(d:AcquisitionDraft,id?:string)=>{const old=acqs.find(x=>x.id===id);const r=await fetch(`/api/gestion/investment/acquisitions${id?`/${id}`:""}`,{method:id?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(id?{draft:d,expectedUpdatedAt:old?.updatedAt}:d)});if(!r.ok)throw Error("save");const x=(await r.json()).record;setAcqs(v=>[...v.filter(q=>q.id!==x.id),x]);};if(loading)return <div className="investment-workspace"><section className="investment-panel">{copy.loading}</section></div>;return <div className="investment-workspace">{section==="loans"?<Loans locale={locale} properties={properties} records={loans} readOnly={datasetId!=="real"} onSave={saveLoan}/>:<Acquisitions locale={locale} records={acqs} readOnly={datasetId!=="real"} onSave={saveAcq}/>}</div>}
