// Assembles the migrations the end-to-end database is built from, in the
// layout the Supabase CLI expects (e2e/supabase/migrations, timestamped):
//
//   1. a prelude that makes a fresh local stack look like the project the
//      schema was written against (publication, extensions);
//   2. Morada's own migrations, vendored in e2e/db/morada (see MANIFEST.md);
//   3. this repository's supabase/applied files, in order, minus the
//      rollback script.
//
// The output directory is generated and ignored by git. Nothing here is a
// migration for production: production is applied by hand, file by file,
// as supabase/applied/APPLIQUE.md records.
import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "../..");
const out = path.join(root, "e2e/supabase/migrations");
rmSync(out, { recursive: true, force: true });
mkdirSync(out, { recursive: true });

const prelude = `-- Generated by e2e/db/prepare.mjs. A fresh local stack, made to look like
-- the hosted project the schema was written against.
create extension if not exists pgcrypto;
create extension if not exists pg_cron;
do $$
begin
  if not exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    create publication supabase_realtime;
  end if;
end
$$;
`;
writeFileSync(path.join(out, "20260101000000_e2e_prelude.sql"), prelude);

const morada = path.join(here, "morada");
const moradaFiles = readdirSync(morada).filter((f) => f.endsWith(".sql")).sort();
for (const f of moradaFiles) writeFileSync(path.join(out, f), readFileSync(path.join(morada, f)));

const applied = path.join(root, "supabase/applied");
const gestionFiles = readdirSync(applied)
  .filter((f) => /^\d{4}_.*\.sql$/.test(f) && !f.startsWith("0099"))
  .sort();
gestionFiles.forEach((f, i) => {
  // After every Morada file (2026-08-23), in the same order as production.
  const stamp = `2027010100${String(i + 1).padStart(4, "0")}`;
  writeFileSync(path.join(out, `${stamp}_gestion_${f}`), readFileSync(path.join(applied, f)));
});

console.log(`${1 + moradaFiles.length + gestionFiles.length} migrations assembled in ${path.relative(root, out)}: prelude, ${moradaFiles.length} Morada, ${gestionFiles.length} gestion`);
