import type { InvestmentCopy } from "./fr";

export const investmentDe = {
  allocationNeeded: "Diese Einheit teilt einen Gebäudekredit. Verwenden Sie die Gesamtübersicht, bis die Finanzierung auf die Einheiten aufgeteilt ist.", unitScopeHint: "Prognose für die gewählte Einheit und ihre direkt zugeordneten Kredite. Kautionen und Mietnebenkosten sind ausgeschlossen.",
  loans: "Immobilienkredite", acquisitions: "Kaufprojekte", simulator: "Kauf planen",
  loansHint: "Ihre Rückzahlungen, Restschulden und verfügbaren Mieteinnahmen.",
  addLoan: "Kredit hinzufügen", editLoan: "Kredit bearbeiten", save: "Kredit speichern", cancel: "Abbrechen", back: "Zurück", next: "Weiter", close: "Schließen", edit: "Bearbeiten", details: "Details ansehen",
  monthly: "Monatliche Rückzahlungen", monthlyHint: "Geschätzte Tilgung und Zinsen, ohne Versicherung.", outstanding: "Restschuld", outstandingHint: "Aus den zuletzt eingetragenen Salden.", active: "Laufend", repaid: "Zurückgezahlt", unknown: "Finanzierung nicht erfasst", all: "Alle Kredite", filter: "Anzeigen", noMatch: "Keine Kredite in dieser Auswahl.",
  emptyTitle: "Jede Rückzahlung bringt Sie Ihrem Ziel näher.", emptyHint: "Tragen Sie den Saldo Ihres Bankauszugs ein. So sehen Sie die verbleibende Schuld und die Auswirkung auf Ihre Mieteinnahmen.", noProperty: "Fügen Sie zuerst eine Immobilie hinzu, der Sie den Kredit zuordnen können.", addProperty: "Immobilie hinzufügen", unknownHint: "Eine Immobilie ohne erfassten Kredit gilt nicht automatisch als schuldenfrei.",
  stepProperty: "Immobilie und Bank", stepBalance: "Rückzahlung", stepReview: "Prüfen", property: "Immobilie", unit: "Einheit", wholeProperty: "Gesamte Immobilie", name: "Kreditname", bank: "Bank", original: "Ursprünglicher Kredit (€)", balance: "Saldo laut Auszug (€)", balanceDate: "Datum des Auszugs", rate: "Nominaler Jahreszins (%)", ratePoints: "Prozentpunkte", rateType: "Zinsart", fixed: "Fest", variable: "Variabel", mixed: "Gemischt", remaining: "Verbleibende Monatsraten", insurance: "Versicherung pro Monat (€)", nextPayment: "Nächste Fälligkeit", fixedUntil: "Ende der Zinsbindung", notes: "Notizen", optional: "Optional", choose: "Immobilie wählen", paidHint: "Bei einem getilgten Kredit tragen Sie für den Saldo und die verbleibenden Raten jeweils null ein.", rateHint: "Verwenden Sie den nominalen Vertragszins, nicht den effektiven Jahreszins. Erfassen Sie jeden Teil eines gemischten Kredits separat.", invalid: "Prüfen Sie Beträge, Daten und Pflichtfelder. Restschuld und Restlaufzeit müssen zusammenpassen.", failed: "Der Kredit konnte nicht gespeichert werden. Ihre Angaben bleiben im Formular erhalten. Versuchen Sie es erneut.", saved: "Kredit gespeichert.", readOnly: "Die Beispielverwaltung ist schreibgeschützt. Der Rechner bleibt verfügbar.", unavailable: "Die Kredite konnten nicht geladen werden. Versuchen Sie es später erneut.",
  repaidCapital: "Getilgtes Kapital", increased: "Der Saldo übersteigt den ursprünglichen Kredit. Prüfen Sie eine mögliche Umschuldung oder aktualisieren Sie den Auszug.", ofOriginal: "des ursprünglichen Kredits", monthsLeft: "geplante Raten verbleibend", confirmedOn: "Saldo erfasst am", schedule: "Voraussichtlicher Tilgungsplan", scheduleHint: "Bei unverändertem Zinssatz und einem Tilgungskredit mit gleichbleibenden Monatsraten. Die Berechnung bestätigt keine Bankzahlung.", month: "Rate", principal: "Tilgung", interest: "Zinsen", payment: "Monatsrate", loanBalance: "Restschuld", totalInterest: "Geschätzte verbleibende Zinsen", fullSchedule: "Jahresbeträge ansehen", year: "Jahr", balanceTrend: "Voraussichtliche Entwicklung der Restschuld", insuranceLabel: "Monatliche Versicherung", totalOutflow: "Monatlicher Abfluss mit Versicherung", bankLinks: "Banken in Luxemburg", bankLinksHint: "Informieren Sie sich direkt über die Angebote. Zinsen und Bedingungen hängen von Ihrem Antrag ab.",
  profitability: "Was Ihre Immobilie erwirtschaften könnte", profitabilityHint: "Monatliche Prognose anhand der Mieten laufender Mietverträge. Sie zeigt keine tatsächlichen Bankeingänge.", rent: "Miete ohne Nebenkosten", ownerCosts: "Eigentümerkosten/Monat (€)", costsHint: "Nicht umlagefähige Kosten, Instandhaltung, Steuern und Rücklagen. Tragen Sie Ihr Budget für ein genaueres Ergebnis ein.", occupancy: "Geschätzte Auslastung (%)", acquisitionCost: "Gesamte Anschaffungskosten (€)", netCash: "Verfügbar nach Kreditrate", beforeCosts: "Vor noch nicht erfassten Eigentümerkosten", netYield: "Geschätzte operative Rendite", afterCosts: "Nach erfassten Kosten, vor persönlicher Besteuerung", scopeHint: "Kredite werden je Immobilie zusammengefasst, damit eine Finanzierung nicht doppelt zählt. Mietkautionen und Nebenkosten der Mieter sind ausgeschlossen.",
  simulatorHint: "Planen Sie Ihr Eigenkapital und prüfen Sie, wie sich ein Kauf auf Ihr Budget auswirken könnte.", projectStep: "Ihr Vorhaben", budgetStep: "Ihr Eigenkapital", resultStep: "Ihre Prognose", price: "Kaufpreis (€)", proposedLoan: "Geplanter Kredit (€)", fees: "Kauf- und Kreditkosten (€)", feesHint: "Stimmen Sie das Budget mit Notar und Bank ab. Berücksichtigen Sie Abgaben, Honorare und Kosten für Sicherheiten. Steuervergünstigungen werden nicht automatisch abgezogen.", works: "Geplante Arbeiten (€)", reserve: "Verbleibende Reserve (€)", term: "Kreditlaufzeit (Jahre)", cash: "Verfügbare Ersparnisse (€)", saving: "Monatliche Ersparnis (€)", savingHint: "Was nach laufenden Krediten und sonstigen Ausgaben übrig bleibt. Der Betrag kann null oder negativ sein.", income: "Haushaltsnetto/Monat (€)", existingDebt: "Laufende Monatsraten (€)", expectedRent: "Erwartete Monatsmiete (€)", stressRate: "Zinsanstieg testen (Prozentpunkte)", calculate: "Prognose ansehen", change: "Annahmen anpassen", targetReached: "Eigenkapitalziel erreicht", targetMonths: "Monate bis zum Eigenkapitalziel", notReached: "Mit dieser monatlichen Ersparnis wird das Ziel nicht erreicht.", cashTarget: "Benötigtes Eigenkapital und Reserve", gap: "Noch anzusparen", monthlyEstimate: "Neue monatliche Kreditrate", debtRatio: "Kreditraten / Haushaltseinkommen", ratioHint: "Laufende und neue Kreditraten, ohne Mieteinnahmen und Versicherungen. Diese Quote ist keine Kreditzusage.", stress: "Bei steigendem Zinssatz", scenarioNote: "Unverbindliche Simulation, keine Finanzberatung oder Zusage einer Finanzierung. Zinssatz, Kosten und Mieten beruhen auf Ihren Annahmen. Kredite mit Zahlungsaufschub oder endfälliger Tilgung erfordern eine andere Berechnung.", notSaved: "Die Annahmen bleiben auf dieser Seite und verändern Ihre Konten nicht.", sources: "Finanzierung in Luxemburg verstehen", sourcesHint: "Offizielle Quellen und Referenzrechner, abgerufen am 27. September 2026.", sourceCssf: "CSSF: Bedingungen für Immobilienkredite", sourceNotary: "Chambre des notaires: einen Kauf vorbereiten", sourceAthome: "atHome Finance: Immobilienkreditrechner", sourceFees: "Guichet.lu: Kosten und Steuergutschrift", resultMissing: "Füllen Sie die Felder aus, um die Prognose zu berechnen.", units: "Einheiten", noLoans: "Kein Kredit für diese Immobilie erfasst", notAnApproval: "Das Eigenkapital ist ein Sparziel. Die Bank muss die Finanzierung noch prüfen.",
} satisfies InvestmentCopy;
