import type { InvestmentCopy } from "./fr";

export const investmentEn = {
  allocationNeeded: "This unit shares a building mortgage. Use the whole-property projection until the financing has been allocated between units.", unitScopeHint: "Projection for the selected unit and mortgages linked directly to it. Deposits and tenant service charges are excluded.",
  loans: "Mortgages", acquisitions: "Purchase projects", simulator: "Plan a purchase",
  loansHint: "Your repayments, outstanding balances and income after property costs.",
  addLoan: "Add a mortgage", editLoan: "Edit mortgage", save: "Save mortgage", cancel: "Cancel", back: "Back", next: "Continue", close: "Close", edit: "Edit", details: "View details",
  monthly: "Monthly repayments", monthlyHint: "Estimated principal and interest, excluding insurance.", outstanding: "Outstanding principal", outstandingHint: "Based on the latest balances entered.", active: "Active", repaid: "Repaid", unknown: "Financing not recorded", all: "All mortgages", filter: "Show", noMatch: "No mortgages match this selection.",
  emptyTitle: "Each repayment brings you closer to your goal.", emptyHint: "Add the balance from your bank statement to see what remains to be repaid and how it affects your rental income.", noProperty: "Add a property to your portfolio before linking a mortgage to it.", addProperty: "Add a property", unknownHint: "A property without a recorded mortgage is not treated as mortgage-free.",
  stepProperty: "Property and bank", stepBalance: "Repayments", stepReview: "Review", property: "Property", unit: "Unit", wholeProperty: "Whole property", name: "Mortgage name", bank: "Bank", original: "Original loan (€)", balance: "Statement balance (€)", balanceDate: "Statement date", rate: "Nominal annual rate (%)", ratePoints: "points", rateType: "Rate type", fixed: "Fixed", variable: "Variable", mixed: "Mixed", remaining: "Payments remaining", insurance: "Monthly insurance (€)", nextPayment: "Next payment date", fixedUntil: "Fixed-rate period ends", notes: "Notes", optional: "Optional", choose: "Choose a property", paidHint: "For a repaid mortgage, enter zero for both the balance and payments remaining.", rateHint: "Use the nominal contract rate, not the APR. Enter each part of a mixed-rate loan separately.", invalid: "Check the amounts, dates and required fields. The balance and remaining term must be consistent.", failed: "The mortgage could not be saved. Your entries are still in this form. Try again.", saved: "Mortgage saved.", readOnly: "The sample agency is read-only. You can still use the calculator.", unavailable: "Mortgages could not be loaded. Try again later.",
  repaidCapital: "Principal repaid", increased: "The balance exceeds the original loan. Check whether the mortgage was refinanced or the statement needs updating.", ofOriginal: "of the original loan", monthsLeft: "scheduled payments remaining", confirmedOn: "Balance recorded on", schedule: "Projected repayment schedule", scheduleHint: "Assumes an unchanged rate and a repayment loan with equal monthly payments. This calculation does not confirm any bank payment.", month: "Payment", principal: "Principal", interest: "Interest", payment: "Monthly payment", loanBalance: "Balance", totalInterest: "Estimated remaining interest", fullSchedule: "View yearly amounts", year: "Year", balanceTrend: "Projected outstanding principal", insuranceLabel: "Monthly insurance", totalOutflow: "Monthly outflow including insurance", bankLinks: "Banks in Luxembourg", bankLinksHint: "Check offers directly with each bank. Rates and terms depend on your application.",
  profitability: "What your property could generate", profitabilityHint: "Monthly projection based on rent from active leases. These figures are not bank receipts.", rent: "Rent excluding service charges", ownerCosts: "Monthly owner costs (€)", costsHint: "Non-recoverable charges, maintenance, taxes and reserves. Enter your budget to refine the result.", occupancy: "Estimated occupancy (%)", acquisitionCost: "Total acquisition cost (€)", netCash: "Available after repayments", beforeCosts: "Before owner costs that have not been entered", netYield: "Estimated operating yield", afterCosts: "After entered costs, before personal tax", scopeHint: "Mortgages are grouped by property to avoid counting the same financing twice. Security deposits and tenant service charges are excluded.",
  simulatorHint: "Plan your down payment and see how a new purchase could affect your budget.", projectStep: "Your project", budgetStep: "Your down payment", resultStep: "Your projection", price: "Property price (€)", proposedLoan: "Planned borrowing (€)", fees: "Purchase and loan costs (€)", feesHint: "Confirm this budget with your notary and bank. Include duties, professional fees and security costs. No tax relief is deducted automatically.", works: "Planned works (€)", reserve: "Reserve to keep (€)", term: "Loan term (years)", cash: "Available savings (€)", saving: "Monthly savings (€)", savingHint: "What you can set aside after existing loan payments and other expenses. This can be zero or negative.", income: "Household net / month (€)", existingDebt: "Loan payments / month (€)", expectedRent: "Expected monthly rent (€)", stressRate: "Rate increase to test (points)", calculate: "View my projection", change: "Adjust assumptions", targetReached: "Down payment target reached", targetMonths: "months to reach your down payment target", notReached: "Your target cannot be reached with these monthly savings.", cashTarget: "Down payment and reserve needed", gap: "Still to save", monthlyEstimate: "New monthly loan payment", debtRatio: "Loan payments / household income", ratioHint: "Existing and new loan payments, excluding rental income and insurance. This ratio is not a bank approval.", stress: "If the rate rises", scenarioNote: "Illustrative simulation, not financial advice or a promise of mortgage approval. Rate, cost and rent assumptions are yours. Deferred-payment and interest-only loans need a different calculation.", notSaved: "These assumptions stay on this page and do not change your accounts.", sources: "Understanding financing in Luxembourg", sourcesHint: "Official sources and reference tools consulted on 27 September 2026.", sourceCssf: "CSSF: mortgage lending conditions", sourceNotary: "Chambre des notaires: preparing a purchase", sourceAthome: "atHome Finance: mortgage calculator", sourceFees: "Guichet.lu: purchase costs and tax credit", resultMissing: "Complete the fields to calculate your projection.", units: "Units", noLoans: "No mortgage recorded for this property", notAnApproval: "The down payment is a savings target. The bank still needs to assess the financing.",
} satisfies InvestmentCopy;
