import type { InvestmentCopy } from "./fr";

export const investmentLu = {
  allocationNeeded: "Dës Eenheet deelt e Kredit vum Gebai. Benotzt d’Projektioun vum ganze Gebai, bis d’Finanzéierung op d’Eenheete verdeelt ass.", unitScopeHint: "Projektioun fir déi ausgewielten Eenheet an déi direkt zougeuerdent Kreditter. Kautiounen a Locatiounschargë sinn ausgeschloss.",
  loans: "Immobilieprêten", acquisitions: "Kafprojeten", simulator: "E Kaf plangen",
  loansHint: "Är Remboursementer, Reschtscholden an disponibel Mietakommes.",
  addLoan: "E Prêt derbäisetzen", editLoan: "Prêt änneren", save: "Prêt späicheren", cancel: "Ofbriechen", back: "Zréck", next: "Weider", close: "Zoumaachen", edit: "Änneren", details: "Detailer kucken",
  monthly: "Remboursementer pro Mount", monthlyHint: "Geschate Kapital an Zënsen, ouni Versécherung.", outstanding: "Reschtschold", outstandingHint: "Op Basis vun de leschten aginnene Salden.", active: "Leeft", repaid: "Zeréckbezuelt", unknown: "Finanzéierung net erfaasst", all: "All Prêten", filter: "Weisen", noMatch: "Keng Prêten an dëser Auswiel.",
  emptyTitle: "All Remboursement bréngt Iech méi no un Äert Zil.", emptyHint: "Gitt de Saldo vun Ärem Bankauszuch an. Dir gesitt, wat nach zeréckzebezuelen ass a wéi sech dat op Är Mietakommes auswierkt.", noProperty: "Setzt fir d’éischt eng Immobilie an Äre Patrimoine derbäi, fir e Prêt domat ze verknëppen.", addProperty: "Eng Immobilie derbäisetzen", unknownHint: "Eng Immobilie ouni erfaasste Prêt gëllt net automatesch als scholdefräi.",
  stepProperty: "Immobilie a Bank", stepBalance: "Remboursement", stepReview: "Iwwerpréiwen", property: "Betraffen Immobilie", unit: "Betraffene Lot", wholeProperty: "Déi ganz Immobilie", name: "Numm vum Prêt", bank: "Bank", original: "Urspréngleche Prêt (€)", balance: "Saldo vum Auszuch (€)", balanceDate: "Datum vum Auszuch", rate: "Nominale Joreszënssaz (%)", ratePoints: "Prozentpunkten", rateType: "Zort Zënssaz", fixed: "Fest", variable: "Variabel", mixed: "Gemëscht", remaining: "Verbleiwend Mountsraten", insurance: "Versécherung pro Mount (€)", nextPayment: "Nächst Fällegkeet", fixedUntil: "Enn vum feste Zënssaz", notes: "Notizen", optional: "Fakultativ", choose: "Eng Immobilie wielen", paidHint: "Bei engem zeréckbezuelte Prêt gitt null fir de Saldo an d’Zuel vun de verbleiwende Raten an.", rateHint: "Benotzt den nominalen Zënssaz aus dem Kontrakt, net den TAEG. Erfaasst all Deel vun engem gemëschte Prêt separat.", invalid: "Iwwerpréift d’Beträg, d’Datumer an d’Flichtfelder. De Saldo an d’Reschtlafzäit mussen zesummepassen.", failed: "De Prêt konnt net gespäichert ginn. Är Angaben bleiwen am Formulaire erhalen. Probéiert nach eng Kéier.", saved: "Prêt gespäichert.", readOnly: "De Beispillcabinet kann net geännert ginn. De Rechner bleift disponibel.", unavailable: "D’Prête konnten net geluede ginn. Probéiert et méi spéit nach eng Kéier.",
  repaidCapital: "Zeréckbezuelt Kapital", increased: "De Saldo ass méi héich wéi den urspréngleche Prêt. Iwwerpréift eng méiglech Refinanzéierung oder aktualiséiert den Auszuch.", ofOriginal: "vum urspréngleche Prêt", monthsLeft: "geplangte Raten iwwreg", confirmedOn: "Saldo erfaasst den", schedule: "Viraussiichtleche Remboursementsplang", scheduleHint: "Bei onverännertem Zënssaz a fir e Prêt mat gläichbleiwende Mountsraten. Dës Berechnung bestätegt keng Bankbezuelung.", month: "Rate", principal: "Kapital", interest: "Zënsen", payment: "Mountsrate", loanBalance: "Saldo", totalInterest: "Geschate verbleiwend Zënsen", fullSchedule: "Joresbeträg kucken", year: "Joer", balanceTrend: "Viraussiichtlech Entwécklung vun der Reschtschold", insuranceLabel: "Mountsversécherung", totalOutflow: "Ausgab pro Mount mat Versécherung", bankLinks: "Banken zu Lëtzebuerg", bankLinksHint: "Kuckt d’Offeren direkt bei de Banken. Zënssätz a Konditioune hänke vun Ärem Dossier of.",
  profitability: "Wat Är Immobilie kéint abréngen", profitabilityHint: "Mountsprognos op Basis vun de Loyere vun de lafende Bails. Dës Zuele si keng tatsächlech Bankagäng.", rent: "Loyeren ouni Niewekäschten", ownerCosts: "Proprietärskäschten/Mount (€)", costsHint: "Net ëmleeëbar Käschten, Ënnerhalt, Steieren a Reserven. Gitt Äre Budget fir e méi geneeë Resultat an.", occupancy: "Geschate Beleegung (%)", acquisitionCost: "Gesamtkäschte vum Kaf (€)", netCash: "Disponibel nom Prêt", beforeCosts: "Virun nach net erfaasste Proprietärskäschten", netYield: "Geschate Betribsrendement", afterCosts: "No den aginnene Käschten, viru perséinleche Steieren", scopeHint: "Prête gi pro Immobilie zesummegefaasst, fir eng Finanzéierung net duebel ze zielen. Mietgarantien an Niewekäschte vun de Locataire sinn ausgeschloss.",
  simulatorHint: "Plangt Äert Eegekapital a kuckt, wéi en neie Kaf Äre Budget kéint beaflossen.", projectStep: "Äre Projet", budgetStep: "Äert Eegekapital", resultStep: "Är Prognos", price: "Präis vun der Immobilie (€)", proposedLoan: "Geplangte Prêt (€)", fees: "Kaf- a Prêtkäschten (€)", feesHint: "Confirméiert dëse Budget mam Notaire a mat der Bank. Rechent Taxen, Honorairen a Käschte fir Garantien mat an. Keng steierlech Hëllef gëtt automatesch ofgezunn.", works: "Geplangten Aarbechten (€)", reserve: "Reserv fir ze behalen (€)", term: "Lafzäit vum Prêt (Joer)", cash: "Disponibel Erspuernisser (€)", saving: "Mountserspuernis (€)", savingHint: "Wat Dir no Äre lafende Prêten an aneren Ausgabe kënnt op d’Säit leeën. De Betrag ka null oder negativ sinn.", income: "Netto vum Stot/Mount (€)", existingDebt: "Lafend Mountsraten (€)", expectedRent: "Erwaarte Loyer pro Mount (€)", stressRate: "Zënshausse testen (Prozentpunkten)", calculate: "Meng Prognos kucken", change: "Hypotheesen upassen", targetReached: "Eegekapitalzil erreecht", targetMonths: "Méint bis zum Eegekapitalzil", notReached: "Mat dëser Mountserspuernis gëtt d’Zil net erreecht.", cashTarget: "Néidegt Eegekapital a Reserv", gap: "Nach unzespueren", monthlyEstimate: "Nei Mountsrate vum Prêt", debtRatio: "Prêtraten / Akommes vum Stot", ratioHint: "Lafend an nei Prêtraten, ouni Mietakommes a Versécherungen. Dëst Verhältnis ass keen Accord vun der Bank.", stress: "Wann den Zënssaz klëmmt", scenarioNote: "Indicativ Simulatioun, keng Finanzberodung a keng Zouso fir eng Finanzéierung. Zënssaz, Käschten a Loyere baséieren op Ären Hypotheesen. Prête mat Bezuelungsopschub oder Remboursement um Enn brauchen eng aner Berechnung.", notSaved: "D’Hypotheese bleiwen op dëser Säit a veränneren Är Konten net.", sources: "Finanzéierung zu Lëtzebuerg verstoen", sourcesHint: "Offiziell Quellen a Referenzrechner, consultéiert de 27. September 2026.", sourceCssf: "CSSF: Konditioune fir Immobilieprêten", sourceNotary: "Chambre des notaires: e Kaf virbereeden", sourceAthome: "atHome Finance: Immobilieprêtrechner", sourceFees: "Guichet.lu: Käschten a Steierkredit", resultMissing: "Fëllt d’Felder aus, fir d’Prognos ze berechnen.", units: "Loten", noLoans: "Kee Prêt fir dës Immobilie erfaasst", notAnApproval: "D’Eegekapital ass e Spuerzil. D’Bank muss d’Finanzéierung nach iwwerpréiwen.",
} satisfies InvestmentCopy;
