/* eslint-disable @typescript-eslint/no-explicit-any */
import { NextResponse } from "next/server";
import { withOrg, dbError } from "@/lib/gestion/api";
import { getDatasetId } from "@/lib/demo";
import { LOAN_COLUMNS, ACQUISITION_COLUMNS, mapLoanRow, mapAcquisitionRow } from "@/lib/gestion/investment";
import { loanSchema } from "@/lib/investment/loans";
import { acquisitionSchema } from "@/lib/investment/acquisition";

type Kind="loans"|"acquisitions";
const table=(k:Kind)=>k==="loans"?"investment_loans":"acquisition_projects";
const snake=(d:any,k:Kind)=>k==="loans"?{property_id:d.propertyId,unit_id:d.unitId,name:d.name,bank_name:d.bankName,original_cents:d.originalCents,balance_cents:d.balanceCents,balance_date:d.balanceDate,annual_rate_pct:d.annualRatePct,rate_type:d.rateType,remaining_months:d.remainingMonths,insurance_cents:d.insuranceCents,next_payment_date:d.nextPaymentDate,fixed_until:d.fixedUntil,notes:d.notes}:{name:d.name,address:d.address,stage:d.stage,asking_price_cents:d.askingPriceCents,expected_rent_cents:d.expectedRentCents,bank_name:d.bankName,financing_status:d.financingStatus,notary_name:d.notaryName,next_action:d.nextAction,next_action_date:d.nextActionDate,viewing_date:d.viewingDate,compromis_date:d.compromisDate,finance_deadline:d.financeDeadline,notary_appointment_date:d.notaryAppointmentDate,deed_signed_date:d.deedSignedDate,transfer_date:d.transferDate,handover_date:d.handoverDate,notes:d.notes};
export async function GET(_req:Request,{params}:{params:Promise<{kind:string}>}){const {kind}=await params;if(kind!=="loans"&&kind!=="acquisitions")return NextResponse.json({error:"not_found"},{status:404});const c=await withOrg();if(c instanceof NextResponse)return c;const q:any=c.g.from(table(kind));const {data,error}=await q.select(kind==="loans"?LOAN_COLUMNS:ACQUISITION_COLUMNS).eq("org_id",c.org.id).order("updated_at",{ascending:false});if(error)return dbError("investment list",error);return NextResponse.json({records:(data??[]).map((r:any)=>kind==="loans"?mapLoanRow(r):mapAcquisitionRow(r))});}
export async function POST(req:Request,{params}:{params:Promise<{kind:string}>}){const {kind}=await params;if(kind!=="loans"&&kind!=="acquisitions")return NextResponse.json({error:"not_found"},{status:404});if(await getDatasetId()!=="real")return NextResponse.json({error:"sample_read_only"},{status:403});const c=await withOrg();if(c instanceof NextResponse)return c;const body=await req.json().catch(()=>null);const parsed=(kind==="loans"?loanSchema:acquisitionSchema).safeParse(body);if(!parsed.success)return NextResponse.json({error:"invalid_record",issues:parsed.error.flatten()},{status:400});const q:any=c.g.from(table(kind));const {data,error}=await q.insert({...snake(parsed.data,kind),org_id:c.org.id}).select(kind==="loans"?LOAN_COLUMNS:ACQUISITION_COLUMNS).single();if(error)return dbError("investment create",error);return NextResponse.json({record:kind==="loans"?mapLoanRow(data):mapAcquisitionRow(data)},{status:201});}
